version: '3'
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    ports:
      - "8080:8080"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - springboot
